import Footer from "@/components/ui/footer";
import Header from "@/components/ui/header";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";
import AppBar from "@/components/ui/app-bar";
import { ClientContextProvider } from "@/contexts/client-context";
import localFont from "next/font/local"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const kalamehFont = localFont({
  src:"./kalameh.ttf"
})
 

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={kalamehFont.className}>
      <body className="antialiased">
        <ClientContextProvider>
          <Header />
          {children}
          <Footer />
          <AppBar />
        </ClientContextProvider>
      </body>
    </html>
  );
}
